Lesson1
Pavlmir/data-bases-PyQT-gb pull request #1
Opened 2021-07-08 17:49 UTC by Pavlmir

2021-07-08 21:59 UTC, Ma007ks requested changes

2021-07-08 21:59 UTC, Ma007ks commented on chat/logs/client.log
> +2021-07-08 20:46:54,994 - INFO - client: start_client - Запуск клиента
Хранить логи в репозитории - плохая практика 🙂
Советую посмотреть https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring

2021-07-08 21:59 UTC, Ma007ks commented on chat/logs/config/client_config_log.py
> +import logging.handlers
Рекомендация: вынести модуль `config` на уровень ниже

2021-07-08 21:59 UTC, Ma007ks commented on chat/start_many_clients.py
> +        for user in user_lists[:8]:
Часть с `[:8]` нужно убрать

2021-07-08 21:59 UTC, Ma007ks commented on chat/start_many_clients.py
> +    elif user_command == 's':
Если мы дважды запустим, то будет два юзера с ником `User1`? 🙂

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/launcher_2cli.py
> +while True:
Идея с циклом классная, но это в теории может повлечь ошибки
Давай сделаем без цикла

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/launcher_2cli.py
> +        if sys.platform.find('win') >= 0:
Платформа определяется несколько раз
Может это можно оптимизировать? 🙂

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/lesson1.py
> +            f'77.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(0,255)}')
Почему 77?

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/lesson1.py
> +def random_ipv4(foo: int) -> list:
Имя аргумента не очень подходящее 🙂

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/lesson1.py
> +def host_ping(bar: list):
Здесь тоже имя стоит поменять

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/lesson1.py
> +        bar = []
Здесь тоже имена подправить

2021-07-08 21:59 UTC, Ma007ks commented on lesson1/lesson1.py
> +def host_range_ping_tab(bar: list) -> str:
Здесь тоже имя изменить

2021-07-11 10:23 UTC, Pavlmir commented on chat/logs/client.log
> +2021-07-08 20:46:54,994 - INFO - client: start_client - Запуск клиента
Ок, исправил

2021-07-11 11:10 UTC, merged